### ISSUE TITLE
hexo g 报错请指点

### ISSUE THREAD

**Issue by roryshanshan** [lete114/hexo-theme-MengD#2]
FATAL {
  err: TypeError: Cannot set property 'path' of undefined
      at Hexo.<anonymous> (C:\Users\12613\Desktop\hexo\themes\MengD\scripts\replace_config.js:14:22)
      at Hexo.emit (events.js:327:22)
      at Hexo._generate (C:\Users\12613\Desktop\hexo\node_modules\hexo\lib\hexo\index.js:452:10)
      at C:\Users\12613\Desktop\hexo\node_modules\hexo\lib\hexo\index.js:356:19
      at tryCatcher (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:673:18)
      at PromiseArray._resolve (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise_array.js:145:14)
      at Promise._settlePromise (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:609:26)
      at Promise._settlePromise0 (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\12613\Desktop\hexo\node_modules\bluebird\js\release\async.js:93:12)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by lete114** [comment]
你克隆的是最新dev分支吗？

**Comment by lete114** [comment]
目前已经发布最新版v1.6.0正式版，如有问题，欢迎提出，感谢你的支持
